    zn "HSLIB"
    set namespace="FHIRPROFILE"
    // Install a Foundation namespace and change to it
    Do ##class(HS.Util.Installer.Foundation).Install(namespace)
    zn namespace
    Set strategyClass = "HS.FHIRServer.Storage.JsonAdvSQL.InteractionsStrategy"
    Set appKey = "/csp/healthshare/fhirprofile/fhir/r4"
    Set metadataPackages = $lb("hl7.fhir.r5.core@5.0.0")
    Do ##class(HS.FHIRServer.Installer).InstallInstance(appKey,strategyClass, metadataPackages,,"Testing fhir profile",0)
    halt